openapi: "3.0.0"
info:
  title: Tshirt store API
  description: LCO - a course to create API for ecomm store
  version: 1.1.0
  contact:
    email: hitesh@lco.dev
    url: "https://lco.dev"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for local host - secure
#   - url: "http://localhost:4000/api/v1"
#     description: for local host - regular

servers:
  - url: "{protocol}://{url}/api/{version}"
    description: for local host 
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      url:
        enum:
          - localhost:4000